export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const LAUNCH_SEARCH = 'LAUNCH_SEARCH';
export const SAVE_SEARCH_TERM = 'SAVE_SEARCH_TERM';
